### ISSUE TITLE
change attributes for sun chance names

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#123]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

to be according to the description in the docs:
```
Sun chance today, tomorrow and day after tomorrow
```

which is more friendly than the current sun_chance0/1/2 

check what we did before, and have to do now:

### Additional information

```
        entities:
          - entity: binary_sensor.knmi_zon
            name: Vandaag
            attribute: sun_chance0 #Zonkans vandaag
          - entity: binary_sensor.knmi_zon
            name: Morgen
            attribute: sun_chance1 #Zonkans morgen
          - entity: binary_sensor.knmi_zon
            name: Overmorgen
            attribute: sun_chance2 #Zonkans overmorgen

```
