### ISSUE TITLE
Weather.get_forecasts - sensor/attribute issue

### ISSUE THREAD

**Issue by dutch-erik** [golles/ha-knmi#125]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

When creating the following template sensor the attributes are not created correctly.
```
action:
    - service: weather.get_forecasts
      data:
        type: daily
      target:
        entity_id: weather.knmi_home
      response_variable: daily
  sensor:
    - name: KNMI weersverwachting 5 dagen
      unique_id: knmi_home_weersverwachting_5dagen
      icon: mdi:weather-cloudy
      state: "{{ daily['weather.knmi_home'].forecast[0].condition }}"
      attributes:
        forecast: "{{ daily['weather.knmi_home'].forecast }}"

```
![030b681a71863a3ba072e1483330133338e29a71](https://github.com/golles/ha-knmi/assets/62548287/9eb04f15-71d4-4722-a605-39e89d60f816)

[https://community.home-assistant.io/t/weather-get-forecasts-sensor-attribute-issue/696671](url)
"Looks to me like an error in the integration — the datetime should be a string (as produced by isoformat()) but is coming across as a datetime object that can’t be serialised into JSON."

Does this sound familiar to you?

### Integration version

2.0.0

### Home Assistant version

core-2024.2.4

### Python version

3.12.1
