### ISSUE TITLE
Created sensors for all available information

### ISSUE THREAD

**Issue by dutch-erik** [golles/ha-knmi#28]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

Hi, 
First of all thank you this helpful component.
Would it be possible to create sensors for all API-information?
This would be very very useful. 
Thank you very much. ;) 

### Additional information

<html><body>

liveweer |  
-- | --
0 |  
plaats | "Amsterdam"
temp | "21.1"
gtemp | "19.2"
samenv | "Onbewolkt"
lv | "51"
windr | "NW"
windrgr | "315"
windms | "4"
winds | "3"
windk | "7.8"
windkmh | "14.4"
luchtd | "1031.4"
ldmmhg | "774"
dauwp | "10"
zicht | "35"
verw | "Zwaar bewolkt en droog"
sup | "05:27"
sunder | "22:04"
image | "zonnig"
d0weer | "halfbewolkt"
d0tmax | "22"
d0tmin | "13"
d0windk | "2"
d0windknp | "6"
d0windms | "3"
d0windkmh | "11"
d0windr | "W"
d0windrgr | "270"
d0neerslag | "0"
d0zon | "48"
d1weer | "bewolkt"
d1tmax | "22"
d1tmin | "12"
d1windk | "3"
d1windknp | "8"
d1windms | "4"
d1windkmh | "15"
d1windr | "NW"
d1windrgr | "315"
d1neerslag | "30"
d1zon | "30"
d2weer | "bewolkt"
d2tmax | "18"
d2tmin | "13"
d2windk | "2"
d2windknp | "6"
d2windms | "3"
d2windkmh | "11"
d2windr | "NW"
d2windrgr | "315"
d2neerslag | "20"
d2zon | "20"
alarm | "0"

</body>
</html>

**Comment by golles** [comment]
Hi Erik,
Most of these fields are covered in this component at this moment, what would you like to see?

I did consider making a KNMI sun sensor in the past, but didn't find it useful as there is already a sun sensor in Home Assistant.

**Comment by dutch-erik** [comment]
Thanks for the quick answer. ;)
What I'm missing for example is:

plaats: de locatie
lv: relatieve luchtvochtigheid
windr: windrichting
winds: windkracht (Beaufort)
d(0-2)windk: Windkracht xxxx (in Bft)
d(0-2)windr: Windrichting xxxx

**Comment by golles** [comment]
I wonder why you would want to know the place from the API, I assume you know for which place you added this integration.
The relative humidity is something I'll add a sensor for.

For the others you can get that with templating:
```yaml
windr: windrichting {{ state_attr("weather.knmi_purmerend", "wind_bearing") }}

winds: windkracht (Beaufort) {{ (((state_attr("weather.knmi_purmerend", "wind_speed") / 3.6)/0.836)**(2/3)) | round }}

d(0-2)windk: Windkracht xxxx (in Bft) 
Today: {{ (((state_attr("weather.knmi_purmerend", "forecast")[0]["wind_speed"] / 3.6)/0.836)**(2/3)) | round }}
Tomorrow: {{ (((state_attr("weather.knmi_purmerend", "forecast")[1]["wind_speed"] / 3.6)/0.836)**(2/3)) | round }}
Day after tomorrow: {{ (((state_attr("weather.knmi_purmerend", "forecast")[2]["wind_speed"] / 3.6)/0.836)**(2/3)) | round }}

d(0-2)windr: Windrichting xxxx 
Today: {{ state_attr("weather.knmi_purmerend", "forecast")[0]["wind_bearing"] }}
Tomorrow: {{ state_attr("weather.knmi_purmerend", "forecast")[1]["wind_bearing"] }}
Day after tomorrow: {{ state_attr("weather.knmi_purmerend", "forecast")[2]["wind_bearing"] }}
```
