### ISSUE TITLE
adjust empty Waarschuwing attribute

### ISSUE THREAD

**Issue by Mariusthvdb** [golles/ha-knmi#70]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

which currently is empty:

<img width="568" alt="Scherm­afbeelding 2023-02-12 om 16 52 56" src="https://user-images.githubusercontent.com/33354141/218321668-1a79d691-70cb-45d7-b04f-421231b9fb77.png">

checking the KNMI api directly via a rest sensor returns:

<img width="440" alt="Scherm­afbeelding 2023-02-12 om 16 54 32" src="https://user-images.githubusercontent.com/33354141/218321715-4aa674f1-abe9-4e4c-a088-c7b92db5ad45.png">

which might be a nice addition to that entity?

### Additional information

```
  - resource: https://cdn.knmi.nl/knmi/xml/rss/rss_KNMIwaarschuwingen.xml
    scan_interval: 900

    sensor:

#       - unique_id: knmi_waarschuwingen_
#         name: KNMI waarschuwingen
#         value_template: >
#           {{now()}}
#         json_attributes_path: '$.rss.channel'
#         json_attributes:
#           - item

      - unique_id: knmi_waarschuwingen_nb
        name: KNMI waarschuwingen NB
        value_template: >
          {{now()}}
        json_attributes_path: "$.rss.channel.item[?(@.title=='Waarschuwingen Noord-Brabant')]"
        json_attributes:
          - title
          - description
          - link
          - guid
          - pubDate
          - author

      - unique_id: knmi_waarschuwingen_basis
        name: KNMI waarschuwingen basis
        value_template: >
          {{now()}}
        json_attributes_path: "$.rss.channel.item[0]"
        json_attributes:
          - title
          - category
          - description
          - enclosure
          - link
          - guid
          - pubDate
          - author
 ```
