### ISSUE TITLE
The knmi integration is using deprecated forecast (2023.9 beta)

### ISSUE THREAD

**Issue by hmmbob** [golles/ha-knmi#87]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

Just leaving this here: if you get this error on b0 of the 2023.8 release, just wait for the final release: it's being fixed in core: https://github.com/home-assistant/core/issues/97290

```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:169
Integration: Weer (documentation, issues)
First occurred: 08:42:28 (1 occurrences)
Last logged: 08:42:28

custom_components.knmi.weather::KnmiWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.
```

### Integration version

1.5.0

### Home Assistant version

core-2023.8.0b0

### Python version

3.11

**Comment by hmmbob** [comment]
To stress: just wait for 2023.8 final release, it's fixed in core (will be deprecated later).

https://github.com/home-assistant/core/issues/97290

**Comment by golles** [comment]
Should be fixed by implementing `async_forecast_daily` instead of `forecast` property, 
I'll be able to do this before the new release.

**Comment by golles** [comment]
I think the latest HA dev build has resolved this issue in https://github.com/home-assistant/core/pull/97292, can you confirm?

**Comment by hmmbob** [comment]
Yes

**Comment by golles** [comment]
#88 is ready but should be merged after HA 2023.8 release

**Comment by golles** [comment]
`async_forecast_daily` Doesn't seem to do anything at this moment, I had my PR merged and realized there was no longer a forecast, 20ee1dc fixes this, and now both methods are supported, once HA decides to make the switch the old one can be removed

**Comment by golles** [comment]
https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/

**Comment by hmmbob** [comment]
Jep, and the newest beta is now (again) complaining about it, including a repairs issue:

![image](https://github.com/golles/ha-knmi/assets/33529490/a08f78ef-50bb-4f80-b0ad-e89506cb0a86)

**Comment by golles** [comment]
I'll fix this somewhere next week after the next release, theoretically reverting 20ee1dc047c3193c82db38415515377e7a416470 should be enough

**Comment by hmmbob** [comment]
Yeah, and as far as I understand nothing will actually break now, it's just a warning

**Comment by golles** [comment]
I've quickly drafted a PR #91 if anyone has time, feel free to test it locally and provide feedback.
I'll wait till the HA 2023.9 update to test (we should merge after the update anyway).

**Comment by hmmbob** [comment]
Eerst ff Formule 1, kan straks wel even testen

**Comment by hmmbob** [comment]
Error is gone, but I guess some more work is needed

![image](https://github.com/golles/ha-knmi/assets/33529490/331011dc-789e-4e2e-b903-56e4118c4928)

By the way, the weather entity does not appear in the entity-chooser (I added it manually), and when calling te service, it errors out.

**Comment by golles** [comment]
I missed a little thing, I've tested against `2023.9.0b3` and I think it should no work as expected, please let me know

**Comment by hmmbob** [comment]
Works!

**Comment by golles** [comment]
> Works!

Thanks. I'll release it in a couple of days. So most of the early updaters are on 2023.9

**Comment by hmmbob** [comment]
You should be good as your hacs.json indicates 2023.9 as minimum version, so people running older versions won't see the update

**Comment by golles** [comment]
Fair enough; https://github.com/golles/ha-knmi/releases/tag/1.6.0

**Comment by golles** [comment]
In case anyone uses forecast in templates/automations like `state_attr("weather.knmi_purmerend", "forecast")[0]["temperature"]`, you now need to use a template sensor to get the forecast data.
(Some of the built-in weather providers are still setting the old/deprecated forecast attribute...)

eg:
```yaml
template:
  - trigger:
      - platform: time_pattern
        minutes: /10
    action:
      - service: weather.get_forecast
        data:
          type: daily
        target:
          entity_id: weather.knmi_purmerend
        response_variable: forecast
    binary_sensor:
      - name: KNMI regen vandaag
        state: "{{ forecast.forecast[0].precipitation_probability > 0 }}"
    sensor:
      - name: KNMI max temp vandaag
        state: "{{ forecast.forecast[0].temperature }}"
```

**Comment by hmmbob** [comment]
I've extended the example a bit in my config, so it get's a value directly on restart & reload and with an unique_id, so you can more easily set icons from the frontend if you'd like:

```yaml
  template:
    - trigger:
        - platform: time_pattern
          hours: /1
        - platform: homeassistant
          event: start
        - platform: event
          event_type: event_template_reloaded
      action:
        - service: weather.get_forecast
          data:
            type: daily
          target:
            entity_id: weather.knmi_home
          response_variable: forecast
      binary_sensor:
        - name: KNMI regen vandaag
          state: "{{ forecast.forecast[0].precipitation_probability > 0 }}"
          unique_id: knmi_regen_vandaag
      sensor:
        - name: KNMI max temp vandaag
          unique_id: knmi_max_temp_vandaag
          state: "{{ forecast.forecast[0].temperature }}"
          availability: "{{ is_number(forecast.forecast[0].temperature) }}"
```

@golles Maybe it's even worth thinking of to provide these two sensors directly from the integration - I think they'll be the most templated sensors anyways.

**Comment by golles** [comment]
I'm very against duplicating unnecessary data, but I was actually considering this as well. 

I think this new way of dealing with the forecast isn't great at all. Maybe it's faster for the ui, but I don't think I've ever noticed it to be slow in the first place and not having to add extra (template) sensors is defeating the whole purpose in my opinion. 

I've also noticed that, at least one (Met.no), built in weather integration is still using the old forecast attribute (combined with the new service). I shouldn't do that as the code mentions not to overwrite that function anymore. Which makes this weather integration look worse than built in ones...

**Comment by hmmbob** [comment]
Geen speld tussen te krijgen.

**Comment by dutch-erik** [comment]
I think you've seen it, but there is a nice discussion about this subject:
[https://community.home-assistant.io/t/petition-dont-delete-the-forecast-attribute/609298](url)

Providing these two sensors directly from the integration would be very helpful.

**Comment by TheFes** [comment]
I know there are ideas to support service calls directly in templates, like 
`{% set forecast = service_call('calendar.get_events', {'entity_id': 'calendar.work', 'start_date_time': today_at(), 'duration': {'hours': 24}}) %}` which would get the result directly. I know one of the HA contributors and templates experts want to implement this, but it requires a lot of coding. He mentioned he would like to have this implemented before the depreciation of the forecast attribute. (my example is for the calendar, but for the weather forecast service call it would be similar)

This will allow the response to be directly used in templates, and then no further (template) sensors would be required.

However, before that, to combine 2 weather forecasts I would have to write them to a template or mqtt sensor. It is not possible to iterate over them in a `repeat`  service call, because of the limited scope of the response (it will only be available in the repeat service call). So for now I would like to continue using the forecast attribute.

**Comment by golles** [comment]
> I think you've seen it, but there is a nice discussion about this subject:
> 
> [https://community.home-assistant.io/t/petition-dont-delete-the-forecast-attribute/609298](url)
> 
> 
> 
> Providing these two sensors directly from the integration would be very helpful.

I wasn't aware of this thread so many thanks for sharing. I'll try to read and comment if needed during the weekend

**Comment by golles** [comment]
@TheFes I do understand your issue but adding support back for the deprecated attribute is maybe nice for the time being but not very future proof. 

I was actually pretty surprised yesterday to see that built in weather integrations are still supporting the attribute. Even though it shouldn't be used anymore https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L553

Let see in the coming days how the thread on the forums evolve, in my  opinion the decision should be taken by HA and this integration should simply follow.

Using the previous version of this integration is indeed maybe the best short therm solution

**Comment by TheFes** [comment]
That's because he policy in HA is that things which are depreciated will be supported for 6 months before being removed. So the forecast attributes will be removed in 2024.3, giving people time to adjust

**Comment by flbderks** [comment]
Damn, I was checking why my automations are not working, well now I know 👎 . Is there ANY chance that attributes forecast will return?

**Comment by dutch-erik** [comment]
Yes you can by creating a template sensor.
A sensor will be created: `sensor.knmi_weersverwachting`

```
  template:
    - trigger:
        - platform: time_pattern
          hours: /1
        - platform: homeassistant
          event: start
        - platform: event
          event_type: event_template_reloaded
      action:
        - service: weather.get_forecast
          data:
            type: daily
          target:
            entity_id: weather.knmi_home
          response_variable: forecast
      sensor:
        - name: KNMI weersverwachting
          unique_id: knmi_weersverwachting
          state: "{{ now().isoformat() }}"
          attributes:
            forecast: "{{ forecast.forecast }}"

```
