### ISSUE TITLE
Reduce update frequency of plugin

### ISSUE THREAD

**Issue by Mrten** [golles/ha-knmi#89]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The request

I'd like to reduce the update frequency of the plugin; I'm pretty much only interested in the forecast and I can't image that being update more than daily.

Additionally, I already have a weerlive API key in use for another project and I don't want to skirt the rules by requesting another API key for the same IP.

I saw an 'SCAN_INTERVAL' in const.py...

**Comment by JC5** [comment]
Even without using the key somewhere else i get regular API limit exceeded errors.

**Comment by HiDiHo01** [comment]
Refresh is nu gezet op 300 (5 minuten) maar de gegevens worden maar iedere
10 minuten ververst.
Scan interval 600 spaart je dus de helft aan api calls.

Op di 15 aug. 2023 08:02 schreef James Cole ***@***.***>:

**Comment by JC5** [comment]
Klinkt goed, kan ik een PR inschieten?

**Comment by HiDiHo01** [comment]
Ja kan. Zelf heb ik een configuratie optie gemaakt zodat ik meerdere
plaatsen kan gebruiken met verschillende intervals. Bijvoorbeeld Amsterdam
om de 600 sec en Den Haag 3600. Utrecht 3600: etc. Als je bij elkaar maar
niet over 300 p/d gaat.

Op di 15 aug. 2023 09:01 schreef James Cole ***@***.***>:

**Comment by golles** [comment]
Personally, I would sign up for multiple keys, the website doesn't mention that that isn't allowed.

**Comment by JC5** [comment]
> > Even without using the key somewhere else i get regular API limit exceeded errors.
> 
> 
> 
> You might get this if you do multiple restarts a day, like 10+

I don't. At most once a week. In the mean time, for today the API key exceeded its limit again. No reboots in between.

**Comment by golles** [comment]
> > > Even without using the key somewhere else i get regular API limit exceeded errors.
> 
> > 
> 
> > 
> 
> > 
> 
> > You might get this if you do multiple restarts a day, like 10+
> 
> 
> 
> I don't. At most once a week. In the mean time, for today the API key exceeded its limit again. No reboots in between. I'll see what I can edit in the code 💪🏻 

Are you using the same key multiple times? With the default config the API is being called 288 times (within the 300 limit)

**Comment by JC5** [comment]
Not to my knowledge, but I could always get a fresh one just in case.

**Comment by Mariusthvdb** [comment]
having disable automatic. polling and using an automation to update
```
  - id: update_weerlive_knmi
    trigger:
      platform: time_pattern
      minutes: '/12'
    condition:
      condition: state
      entity_id:
        - binary_sensor.ha_restarted
        - binary_sensor.automation_integration_reloaded
        - binary_sensor.template_integration_reloaded
      state: 'off'
#       condition: numeric_state
#       entity_id: sensor.sun_solar_elevation
#       above: 10
    action:
      - service: homeassistant.update_entity
        target:
          entity_id:
  #           - sensor.weerlive_voorspelling_morgen
  #           - sensor.weerlive_voorspelling_vandaag
  #           - sensor.weerlive_actueel
          - sensor.weerlive_alarm
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: 283263df2cf63301888cf4096178ffb7
```

I still receive this error:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.knmi
Source: custom_components/knmi/coordinator.py:37
Integration: KNMI (documentation, issues)
First occurred: 5 december 2023 om 23:06:03 (46 occurrences)
Last logged: 12:00:20

Update failed! - API key daily limit exceeded, try again tomorrow
Update failed! - Timeout error fetching information
```

which shouldnt be happening because these updates take place 5 times per hour = 120 a day, per service, so that would make 240 calls..

any thought how this could occur? (also consider Ive disabled triggering upon HA restart, and reload of the automatic. and template integrations
