### ISSUE TITLE
Seems that the forecast has the wrong date on it?

### ISSUE THREAD

**Issue by Mrten** [golles/ha-knmi#94]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

If I run the new service 'weather.get_forecast' on the knmi plugin I seem to get the dates from yesterday:

```
service: weather.get_forecast
data:
  type: daily
target:
  entity_id: weather.knmi_ley
```

It's Sat 23 Sep 9:30 at the moment and the results in the developer tools say:
```
forecast:
  - datetime: "2023-09-22T22:00:00+00:00"
    condition: partlycloudy
    templow: 11
    temperature: 17
    precipitation_probability: 50
    wind_bearing: 225
    wind_speed: 15
    wind_speed_bft: 3
    sun_chance: 23
  - datetime: "2023-09-23T22:00:00+00:00"
    condition: partlycloudy
    templow: 9
    temperature: 19
    precipitation_probability: 10
    wind_bearing: 180
    wind_speed: 11
    wind_speed_bft: 2
    sun_chance: 60
  - datetime: "2023-09-24T22:00:00+00:00"
    condition: partlycloudy
```

If I look at the code I don't see any way how this can happen but I thought I'd report it anyway.

I enabled debug logs, shall report back.

(oh and is it possible that the links and 'my systeminfo buttons' in the Issue:Bug Report form open in a new window?)

### Integration version

1.6.0

### Home Assistant version

core-2023.9.2

### Python version

3.11.5
